
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
      Сборка начата 06.03.2024 9:44:28.
      
      Проект "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:01.13
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/3.28.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
      Сборка начата 06.03.2024 9:44:29.
      
      Проект "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        Обращение к "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:01.05
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/3.28.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-11dnlx"
      binary: "D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-11dnlx"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-11dnlx'
        
        Run Build Command(s): "D:/Programs/Visual Studio 2022/Visual Studio/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_61e7c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
        Сборка начата 06.03.2024 9:44:31.
        
        Проект "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-11dnlx\\cmTC_61e7c.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_61e7c.dir\\Debug\\".
          Создание каталога "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-11dnlx\\Debug\\".
          Создание каталога "cmTC_61e7c.dir\\Debug\\cmTC_61e7c.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_61e7c.dir\\Debug\\cmTC_61e7c.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_61e7c.dir\\Debug\\cmTC_61e7c.tlog\\unsuccessfulbuild".
        ClCompile:
          D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_61e7c.dir\\Debug\\\\" /Fd"cmTC_61e7c.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.37.32824 для x64
          CMakeCCompilerABI.c
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_61e7c.dir\\Debug\\\\" /Fd"cmTC_61e7c.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-11dnlx\\Debug\\cmTC_61e7c.exe" /INCREMENTAL /ILK:"cmTC_61e7c.dir\\Debug\\cmTC_61e7c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-11dnlx/Debug/cmTC_61e7c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-11dnlx/Debug/cmTC_61e7c.lib" /MACHINE:X64  /machine:x64 cmTC_61e7c.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_61e7c.vcxproj -> D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-11dnlx\\Debug\\cmTC_61e7c.exe
        FinalizeBuildStatus:
          Файл "cmTC_61e7c.dir\\Debug\\cmTC_61e7c.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_61e7c.dir\\Debug\\cmTC_61e7c.tlog\\cmTC_61e7c.lastbuildstate".
        Сборка проекта "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-11dnlx\\cmTC_61e7c.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.99
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-jy68vo"
      binary: "D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-jy68vo"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-jy68vo'
        
        Run Build Command(s): "D:/Programs/Visual Studio 2022/Visual Studio/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_7d187.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Версия MSBuild 17.7.2+d6990bcfa для .NET Framework
        Сборка начата 06.03.2024 9:44:32.
        
        Проект "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-jy68vo\\cmTC_7d187.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_7d187.dir\\Debug\\".
          Создание каталога "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-jy68vo\\Debug\\".
          Создание каталога "cmTC_7d187.dir\\Debug\\cmTC_7d187.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_7d187.dir\\Debug\\cmTC_7d187.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
          Обращение к "cmTC_7d187.dir\\Debug\\cmTC_7d187.tlog\\unsuccessfulbuild".
        ClCompile:
          D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7d187.dir\\Debug\\\\" /Fd"cmTC_7d187.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.37.32824 для x64
          CMakeCXXCompilerABI.cpp
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7d187.dir\\Debug\\\\" /Fd"cmTC_7d187.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\Programs\\Visual Studio 2022\\Visual Studio\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-jy68vo\\Debug\\cmTC_7d187.exe" /INCREMENTAL /ILK:"cmTC_7d187.dir\\Debug\\cmTC_7d187.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-jy68vo/Debug/cmTC_7d187.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Projects/IKBFU/Lab_1_01/lab_1_01/Res2/CMakeFiles/CMakeScratch/TryCompile-jy68vo/Debug/cmTC_7d187.lib" /MACHINE:X64  /machine:x64 cmTC_7d187.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_7d187.vcxproj -> D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-jy68vo\\Debug\\cmTC_7d187.exe
        FinalizeBuildStatus:
          Файл "cmTC_7d187.dir\\Debug\\cmTC_7d187.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_7d187.dir\\Debug\\cmTC_7d187.tlog\\cmTC_7d187.lastbuildstate".
        Сборка проекта "D:\\Projects\\IKBFU\\Lab_1_01\\lab_1_01\\Res2\\CMakeFiles\\CMakeScratch\\TryCompile-jy68vo\\cmTC_7d187.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:01.00
        
      exitCode: 0
...
